language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
script:
- "./gradlew build"
deploy:
  provider: heroku
  app: obscure-taiga-95979
  skip_cleanup: true
  api_key:
    secure: HEROKU_API_KEY
